### ISSUE TITLE
compiled version

### ISSUE THREAD

**Issue by mdissel** [arkhipov/acl#1]
Can you release a compiled version?

**Comment by arkhipov** [comment]
Hello, @mdissel 

The easiest way to install the extension is to use the [PGXN client](http://pgxnclient.projects.pgfoundry.org/).

There are lots of different platforms (*nix, MacOS, Windows) and architectures (i386, x64, arm, mips), so it is much easier to compile it on the target system.

**Comment by mdissel** [comment]
hmm easy? i'm on a windows platform with no knowledge of python pip, etc..

**Comment by arkhipov** [comment]
[Here](https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules#Windows_with_Microsoft_Visual_Studio) is a description of the build process using Microsoft Visual Studio. 

Unfortunately, I have no access to a Windows system. If there are any online continuous integration services that support Windows builds, I can try to add it to one of them.

**Comment by mdissel** [comment]
Thanks. I've managed to create pgxn.exe but not sure in what context this executable should run (running in dos prompt gives a "failed to start process" exception

**Comment by arkhipov** [comment]
I hope it is not too late for you, @mdissel. I have added the MSBuild make file and instructions to README.

**Comment by mdissel** [comment]
Thanks! Much easier to download a dll :wink:
