### ISSUE TITLE
Reason for static Oid get_role_oid in acl_oid.c?

### ISSUE THREAD

**Issue by Chri-s** [arkhipov/acl#11]
First of all: I'm no expert in C.

I tried to compile acl for PostgreSQL 11 on Windows 10 and FreeBSD 11.2. Windows 10 was no problem, but compiling it on FreeBSD 11.2 gave this error:

```
acl_oid.c:66:12: error: static declaration of 'get_role_oid' follows non-static declaration
static Oid get_role_oid(const char *name, bool missing_ok);
           ^
/usr/local/include/postgresql/server/utils/acl.h:212:12: note: previous declaration is here
extern Oid      get_role_oid(const char *rolename, bool missing_ok);
                ^
acl_oid.c:390:5: error: static declaration of 'get_role_oid' follows non-static declaration
Oid get_role_oid(const char *name, bool missing_ok)
    ^
/usr/local/include/postgresql/server/utils/acl.h:212:12: note: previous declaration is here
extern Oid      get_role_oid(const char *rolename, bool missing_ok);
                ^
2 errors generated.
gmake: *** [<builtin>: acl_oid.o] Error 1
```
After some googling I found that this was a warning in earlier compiler versions and now this is an error which blocks compliation. The used compiler is "FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)".

This is the function get_role_oid in acl:
https://github.com/arkhipov/acl/blob/a22179c62236b1bfa0e542c9875488163032d200/acl_oid.c#L389-L401

I found that a function with the same name and same code is included in PostgreSQL: https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/acl.c;hb=refs/heads/REL_11_STABLE#l5184
```
/*
 * get_role_oid - Given a role name, look up the role's OID.
 *
 * If missing_ok is false, throw an error if role name not found.  If
 * true, just return InvalidOid.
 */
Oid
get_role_oid(const char *rolname, bool missing_ok)
{
    Oid         oid;

    oid = GetSysCacheOid1(AUTHNAME, CStringGetDatum(rolname));
    if (!OidIsValid(oid) && !missing_ok)
        ereport(ERROR,
                (errcode(ERRCODE_UNDEFINED_OBJECT),
                 errmsg("role \"%s\" does not exist", rolname)));
    return oid;
}
```

I removed the function get_role_oid in acl_oid.c and the declaration in line 66. It compiles and passes the tests.
Since it works and the function does the same as the function from PostgreSQL, is it safe to do this and can the function perhaps be removed in the repository?

**Comment by arkhipov** [comment]
Fixed in 1.0.3.
