### ISSUE TITLE
Inheritance problem

### ISSUE THREAD

**Issue by mariomka** [arkhipov/acl#6]
I need to inherit permissions in three or more levels. If a user has access to level 1 then can access to all levels, if has access to level 2 then can access to level 3 and following. Something like:

![diagram](https://cloud.githubusercontent.com/assets/1822472/25521036/7533b426-2bfe-11e7-8634-ff7a91018f23.png)

The when I add or update acl of Level 1 it is propagated through the children using acl_merge, the problem is that I don't know how to propagate successfully in this case because if I set container parameter to true "i" flag is added and acl isn't applied but if I set container to false level 2 receive acl without 'o' and 'c' flags then next levels don't inherit the permissions.

Example:

Container paramerter is true:

Level 1: ``{a/oc/1=r}``
Level 2: ``{a/hcoi/1=r}`` result of ``acl_merge('{a/oc/1=r}'::ACE_INT8[], '{}', true, true)``
Level 3+: ``{a/hcoi/1=r}`` result of ``acl_merge('{a/hcoi/1=r}'::ACE_INT8[], '{}', true, true)``

Container paramerter is false:

Level 1: ``{a/oc/1=r}``
Level 2+: ``{a/h/1=r}`` result of ``acl_merge('{a/oc/1=r}'::ACE_INT8[], '{}', false, true)``
Level 3+: ``{}`` result of ``acl_merge('{a/h/1=r}'::ACE_INT8[], '{}', false, true)``

How can I deal with this problem?

**Comment by mariomka** [comment]
Ok. Never mind.

I found the solution just after sent the issue.

I need to add only ``c`` flag and set container parameter as true then ``i`` flag isn't added.

Level 1: ``{a/c/1=r}``
Level 2: ``{a/hc/1=r}`` result of ``acl_merge('{a/c/1=r}'::ACE_INT8[], '{}', true, true)``
Level 3+: ``{a/hc/1=r}`` result of ``acl_merge('{a/hc/1=r}'::ACE_INT8[], '{}', true, true)``

**Comment by arkhipov** [comment]
Your first example looks like a bug, I will check it. The second example is incorrect because if you create an ACL for a non-container object, it should not be used as a parent ACL for other objects.
