### ISSUE TITLE
compatible with 9.6 / 10?

### ISSUE THREAD

**Issue by mdissel** [arkhipov/acl#9]
I didn't test it yet, but can we use this extension with postgres 9.6 (and/or the 10 beta release)

**Comment by arkhipov** [comment]
It should be. There are DLLs built against version 9.6.

**Comment by Chri-s** [comment]
I checked it with PostgreSQL 10 on Windows 10 and FreeBSD 11.1. It works as expected.

Only the uuid regression tests fail, because PostgreSQL changed the error message. (They should fail, but the error message is different from the expected error message)
Expected is:
```ERROR:  invalid input syntax for uuid: ""```
PostgreSQL 10 fails with:
```ERROR:  invalid input syntax for type uuid: ""```

**Comment by arkhipov** [comment]
There are DLLs for PG 9.3-15 in version 1.0.3.
